---
image: amscotti/jekyll-build

pipelines:
  custom:
    update-s3:
      - step:
        script:
          - bundle exec jekyll build
           - bundle exec s3_website push
  default:
    - step:
        script:
          - bundle exec jekyll build
  branches:
    master:
      - step:
          script:
            - bundle exec jekyll build
            - bundle exec s3_website push
